### PR TITLE
adding a reaction trigger for digital.gov

### PR DESCRIPTION
**Pull request by jeremyzilar**

### CODE REVIEW

**Comment by afeld** [comment]
Is this preferable to doing it through Slackbot?

**Comment by afeld** [comment]
Oh, nevermind! Test failure seems unrelated.

**Comment by jeremyzilar** [comment]
Thanks @mgwalker — The repo we're trying to add to is: https://github.com/GSA/digitalgov.gov/issues 🎪

**Comment by mgwalker** [comment]
Ah, alas @jeremyzilar, the configuration doesn't allow us to post issues in repos outside of the 18F org.  🙁  Under the hood, we're using [a plugin maintained by Mike Bland](https://github.com/mbland/hubot-slack-github-issues), and it has the [configuration file documented](https://github.com/mbland/slack-emoji-issues#configuration).  We could potentially put in a pull request with him to add a way to override the Github repo org on a per-reaction level, though.

**Comment by jeremyzilar** [comment]
@mgwalker I just posted: https://github.com/mbland/hubot-slack-github-issues/issues/10

**Comment by mgwalker** [comment]
Closing this one.  We can revisit if mbland/hubot-slack-github-issues#10 is ever implemented, but in the meantime, Charlie can't create issues on Github repos outside of the 18F org.  🙁

**Pull request closed without merging**
