### PR TITLE
[WIP] add basic crossposting script

### PR DESCRIPTION
**Pull request by afeld**
From a workshop I did with @wslack, @ertzeid, and @goodnightjj.

### CODE REVIEW

**Comment by afeld** [comment]
Good next step would be to get this working locally...try installing Node 0.10.x locally and getting it to run! Setup instructions should probably be expanded, but I'd recommend using [nvm](https://github.com/creationix/nvm). Workshop notes:

https://docs.google.com/document/d/1G60RwFt6Zvehrdf8Ge7Zcxoehb_dTa3-FtEodlm9YzU/edit

**Comment by wslack** [comment]
@afeld do you want to get this working first and merge them submits PRs to add features, or put my code edits in this PR?

**Comment by wslack** [comment]
Extra features I'm thinking about, FWIW:

- Hubot tells us it crossposted
- Hubot posts the source channel in the XPOST
- Hubot links back to the original message (would eliminate need to quote and carry over content)

**Comment by afeld** [comment]
I don't feel super strongly either way. I guess the documentation comments at the top should be fixed up before merging- want to take a pass at that, at least?

**Comment by wslack** [comment]
Done, I think this can be merged and then I can work on edits in a separate PR. Makes me feel better if the live server mirrors the repo anyhow since I'm not sure how soon I can come back to this properly.

**Pull request merged**
