### PR TITLE
Use official hubot-slack-github-issues npm release

### PR DESCRIPTION
**Pull request by mbland**
Would like to have @melodykramer, @andrewmaier, and @jeremiak look over the rules to make sure they're the way they want them before we merge.

After that, would love to have @afeld do the honors of firing away.

cc: @ccostino @mtorres253

### CODE REVIEW

**Comment by mbland** [comment]
Closes 18F/handbook#399.

**Comment by andrewmaier** [comment]
@mbland So this is only for the handbook, general talk and questions channels? If so, I'll need to update our `contributing.md` file :)

**Comment by mbland** [comment]
@andrewmaier Only for now; @melodykramer mentioned that we may want to see what the influx is like from these channels first before opening it up to every channel. _But_, if y'all feel like living dangerously, we can remove the `channelNames` field for that rule, and the :evergreen_tree: rule will apply _everywhere_.

**Comment by melodykramer** [comment]
Let's wait at least a week just to assess volume and workflow.

**Pull request merged**
